import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";
import AboutUs from "@/components/aboutUs/AboutUs";
import Service from "@/components/services/Service";
import VaCalculation from "@/components/vaCalculator/VaCalculation";
import Testimonial from "@/components/testimonial/Testimonial";
import SendRequest from "@/components/sendRequest/SendRequest";
import Footer from "@/components/footer/Footer";
import Blog from "@/components/blog/Blog";
import OurProject from "@/components/ourProject/OurProject";
import PdfDownload from "@/components/pdfDownload/PdfDownload";
import HowWorks from "@/components/howItWorks/HowWorks";
import ScrollTop from "@/components/scrollTop/ScrollTop";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Header /> */}
        <Banner />

        <PdfDownload />
        <AboutUs />
        <Service />
        <VaCalculation />
        <HowWorks />
        {/* <Testimonial /> */}
        <OurProject />
        <SendRequest />
        <Blog />
      </main>
    </>
  );
}
